#!/bin/bash

# Install coursier
curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond for Scala 2.12
SCALA_VERSION=2.12.10 ALMOND_VERSION=0.9.1
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  --sources --default=true \
  -o ./almond-scala-2.12
./almond-scala-2.12 --install --id scala212 --display-name "Scala (2.12)" \
  --command "java -XX:MaxRAMPercentage=80.0 -jar almond-scala-2.12 --id scala212 --display-name 'Scala (2.12)'" \
  --copy-launcher \
  --metabrowse
rm -f almond-scala-2.12


./coursier fetch dev.zio:zio:1.0.0-RC18-2
./coursier fetch dev.zio:zio-test:1.0.0-RC18-2
./coursier fetch io.prometheus:simpleclient:0.8.1
./coursier fetch io.prometheus:simpleclient_common:0.8.1
./coursier fetch org.typelevel:cats-effect:2.0.0
./coursier fetch sh.almond:almond_2.12:0.9.1
./coursier fetch --sources dev.zio:zio:1.0.0-RC18-2
./coursier fetch --sources sh.almond:almond-spark_2.12:0.9.1

# Install required Jupyter/JupyterLab extensions
jupyter labextension install @jupyterlab/plotly-extension

# Set indentation to two spaces
JUPYTER_CONFIG_DIR=$(jupyter --config-dir)
# Classic notebook
mkdir -p $JUPYTER_CONFIG_DIR/nbconfig/
cat > $JUPYTER_CONFIG_DIR/nbconfig/notebook.json <<- EOF
{
  "CodeCell": {
    "cm_config": {
      "indentUnit": 2
    }
  }
}
EOF
# JupyterLab notebook
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings <<- EOF
{
    "codeCellConfig": {
      "tabSize": 2
    }
}
EOF
# JupyterLab editor
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/plugin.jupyterlab-settings <<- EOF
{
    "editorConfig": {
      "tabSize": 2,
    }
}
EOF
